[PL] [134362869] Handle cascading versions
rentpath/phenotype pull request #5
Opened 2016-11-15 21:33 UTC by pasha

[Support cascading lookup](https://www.pivotaltracker.com/story/show/134362869)

- add rubocop and fix errors

2016-11-16 15:44 UTC, mirineumark requested changes
A few small things, but looks good overall.

2016-11-16 15:44 UTC, mneumark commented on lib/phenotype/call_handler.rb
> +  def status?
I think this name does not describe what it does very well. Maybe `not_found?`

2016-11-16 15:44 UTC, mneumark commented on lib/phenotype/version.rb
> +  VERSION = '0.3.0.beta1'.freeze
Why beta? Why not just bump to 0.3.0? I think the below 1.0.0 implies beta.

2016-11-16 15:44 UTC, mneumark commented on lib/phenotype/versioned_app.rb
> +      Versioner.new(routes: routes, strategies: strategies, env: env).call
Nice refactor 👍

2016-11-16 15:44 UTC, mneumark commented on spec/call_handler_spec.rb
> +      it 'be true' do
You should make this a one liner.

```ruby
it { is_expected.to be_truthy }
```

2016-11-16 15:44 UTC, mneumark commented on spec/call_handler_spec.rb
> +        expect(subject).to be_falsey
Also a one liner:

```ruby
it { is_expected.to be_falsey }
```

2016-11-16 15:44 UTC, mneumark commented on spec/call_handler_spec.rb
> +      it 'be false' do
Also a one liner:

```ruby
it { is_expected.to be_falsey }
```

2016-11-16 15:44 UTC, mneumark commented on spec/versioner_spec.rb
> +            expect(subject).to eql(error_response)
Also a one liner:

```ruby
it { is_expected.to eql error_response }
```

2016-11-16 15:44 UTC, mneumark commented on spec/versioner_spec.rb
> +            expect(subject).to eql(ok_response)
Also a one liner:

```ruby
it { is_expected.to eql ok_response }
```

2016-11-16 15:44 UTC, mneumark commented on spec/versioner_spec.rb
> +          expect(subject).to eql(ok_response)
Also a one liner:

```ruby
it { is_expected.to eql ok_response }
```

2016-11-16 15:44 UTC, mneumark commented on spec/versioner_spec.rb
> +        expect(subject.first).to eql(406)
Also a one liner:

```ruby
its(first) { is_expected.to eql 406 }
```

2016-11-16 16:20 UTC, pasha commented on lib/phenotype/version.rb
> +  VERSION = '0.3.0.beta1'.freeze
so that final will get `0.3.0` just in case if we see any issues and need to create few more beta versions.

2016-11-16 17:05 UTC, pasha commented on spec/versioner_spec.rb
> +        expect(subject.first).to eql(406)
do not want to introduce another gem just for this matcher, updated `subject` to include `.first`

2016-11-16 17:08 UTC, pasha commented on lib/phenotype/call_handler.rb
> +  def status?
updated method name to `not_found?` 👍

2016-11-16 17:34 UTC, mirineumark approved these changes

2016-11-16 17:55 UTC, rkledesma commented on lib/phenotype/call_handler.rb
> +    response[0].is_a?(Numeric) && response[1].is_a?(Hash) && response[2].is_a?(Array)
You could use `first` `second` `third` Array methods here

2016-11-16 18:02 UTC, colinrymer commented
So I'm pretty opposed to the idea that this PR introduces. I think falling back to a previous version of the API is just asking for problems, e.g.:

* How do I ensure my changes to a prior version don't affect the newer versions in a problematic manner?
* How do I handle endpoints that I no longer want to respond to?
* I'm introducing additional work/cognitive overhead - now if I want to see the code for a given version's endpoint, I have to look in the given version, then through each prior version until I find the code I'm looking for.


Instead, if we introduce a new version of an API that has near identical endpoints, we should just copy the old version into the new one. While we're duplicating code, I'm totally okay with it in this scenario, because we're preferring explicit over implicit. We should basically be treating each version as a new codebase, IMO.

2016-11-16 18:07 UTC, pasha commented on lib/phenotype/call_handler.rb
> +    response[0].is_a?(Numeric) && response[1].is_a?(Hash) && response[2].is_a?(Array)
these will be available in rails but not ruby
```
~/source/phenotype on pl/add/cascading_fetch ✗ $ pry
bundle exec pry
ruby-2.2.3-p173 (main):0 > a = [1, 2, 3]
=> [1, 2, 3]
ruby-2.2.3-p173 (main):0 > a.first
=> 1
ruby-2.2.3-p173 (main):0 > a.second
NoMethodError: undefined method `second' for [1, 2, 3]:Array
from (pry):3:in `__pry__'
ruby-2.2.3-p173 (main):0 > a.third
NoMethodError: undefined method `third' for [1, 2, 3]:Array
from (pry):4:in `__pry__'
```

2016-11-16 18:42 UTC, pasha commented
I am partially agreeing with you, but I think any code duplications could introduce more issues.

- This will increase how long specs run especially on larger projects
- If you need to fix some issue in later version which is also an issue in previous versions, you will need to fix it in multiple places.
- To handle no longer supported end point simply return 404 from them(this will not cause additional lookup in previous versions) - not ideal but much less duplication.
- I think it's easier to look through multiple versions when code doesn't get duplicated, if `v3/some/route` doesn't exist you simply look in previous version.

I don't think there is a silver bullet for how to version apps, i just don't like duplicated code, i think it's prone to errors.

2016-11-16 18:50 UTC, rkledesma commented on spec/call_handler_spec.rb
> +    context '200 and X-Cascad' do
Some typos here: should be 'Cascade' and 'success'

2016-11-16 18:51 UTC, rkledesma commented on spec/versioned_app_spec.rb
> +        expect(subject[0]).to eql(406)
might as well use `first` in this file

2016-11-16 18:53 UTC, rkledesma commented on spec/versioner_spec.rb
> +    context 'To Many Strategies' do
'To' should be 'Too'

2016-11-16 18:58 UTC, rkledesma commented
I'm inclined to agree with @colinrymer -- the same thoughts came into my mind as well, particularly about explicitness and cognitive load.

2016-11-16 19:03 UTC, pasha commented on spec/versioned_app_spec.rb
> +        expect(subject[0]).to eql(406)
refactored

2016-11-16 19:03 UTC, pasha commented on spec/versioner_spec.rb
> +    context 'To Many Strategies' do
fixed

2016-11-16 19:03 UTC, pasha commented on spec/call_handler_spec.rb
> +    context '200 and X-Cascad' do
fixed

2016-11-17 14:35 UTC, pasha commented
build ci

2016-11-17 14:46 UTC, pasha commented
build ci

2016-11-17 14:56 UTC, pasha commented
build ci

2016-11-17 14:58 UTC, pasha commented
build ci

2016-11-17 14:58 UTC, pasha commented
build ci

2016-11-17 14:59 UTC, pasha commented
build ci

2016-11-17 14:59 UTC, pasha commented
build ci

2016-11-17 15:04 UTC, pasha commented
build ci

2016-11-17 17:25 UTC, dillo commented
👍

2016-11-17 17:31 UTC, merged